export interface Article {
  id: string;
  title: string;
  category: string;
  readTime: string;
  publishDate: string;
  excerpt: string;
}

export const TRAVEL_GUIDE_ARTICLES: Article[] = [
  // SAFETY & LAWS (8)
  {
    id: "safety-phuket",
    title: "Phuket'te Motosiklet Kullanmak Güvenli Mi?",
    category: "Güvenlik",
    readTime: "8 min",
    publishDate: "2026-06-01",
    excerpt: "Phuket'te motosiklet sürüşünün güvenliği ve temel güvenlik kuralları",
  },
  {
    id: "thai-laws",
    title: "Tayland'da Motosiklet Kuralları ve Cezalar",
    category: "Hukuk",
    readTime: "10 min",
    publishDate: "2026-05-28",
    excerpt: "Trafik kanunları, ehliyet gereksinimleri ve ceza sistemi",
  },
  {
    id: "international-license",
    title: "Uluslararası Ehliyet Tayland'da Gerekli Mi?",
    category: "Dokümanlar",
    readTime: "6 min",
    publishDate: "2026-05-25",
    excerpt: "IDP gereksinimleri, nasıl alınır ve Tayland'da geçerliliği",
  },
  {
    id: "police-checkpoints",
    title: "Tayland'da Polis Kontrolleri - Bilinmesi Gerekenler",
    category: "Güvenlik",
    readTime: "7 min",
    publishDate: "2026-05-22",
    excerpt: "Kontrolde ne yapmalı, ceza sistemı ve hak bilgisi",
  },
  {
    id: "drunk-driving",
    title: "Tayland'da Alkollü Sürüş - Cezalar ve Sonuçları",
    category: "Hukuk",
    readTime: "5 min",
    publishDate: "2026-05-20",
    excerpt: "Alkol sınırı, cezalar ve yasal sonuçlar",
  },
  {
    id: "helmet-laws",
    title: "Tayland'da Kask Kuralları ve Uygulaması",
    category: "Güvenlik",
    readTime: "4 min",
    publishDate: "2026-05-18",
    excerpt: "Kask türleri, gereklilik ve cezalar",
  },
  {
    id: "accident-procedure",
    title: "Motosiklet Kazası Olursa Ne Yapmalı?",
    category: "Güvenlik",
    readTime: "6 min",
    publishDate: "2026-05-16",
    excerpt: "Kaza sonrası yapılması gereken adımlar",
  },
  {
    id: "insurance-claims",
    title: "Tayland'da Motosiklet Sigortası - Tazminat Alma",
    category: "Dokümanlar",
    readTime: "8 min",
    publishDate: "2026-05-14",
    excerpt: "Sigorta tipleri ve tazminat talep süreci",
  },
  // PRACTICAL GUIDES (12)
  {
    id: "fuel-guide",
    title: "Tayland'da Yakıt İstasyonları ve Benzin Fiyatları",
    category: "Pratik",
    readTime: "5 min",
    publishDate: "2026-05-12",
    excerpt: "Yakıt bulma, fiyatlar ve ödeme yöntemleri",
  },
  {
    id: "parking-guide",
    title: "Phuket'te Motosiklet Parkı - Nerede Bırakmalı?",
    category: "Pratik",
    readTime: "5 min",
    publishDate: "2026-05-10",
    excerpt: "Güvenli parkı noktaları ve korunması",
  },
  {
    id: "atm-locations",
    title: "Phuket ATM ve Para Çekme Rehberi",
    category: "Pratik",
    readTime: "4 min",
    publishDate: "2026-05-08",
    excerpt: "ATM konumları ve para işlemleri",
  },
  {
    id: "sim-card",
    title: "Tayland'da SIM Kart - Telefonla Bağlı Kal",
    category: "Pratik",
    readTime: "6 min",
    publishDate: "2026-05-06",
    excerpt: "SIM kart satın alma ve aktivasyon",
  },
  {
    id: "weather-preparation",
    title: "Phuket'te Hava Durumuna Hazırlanma",
    category: "Pratik",
    readTime: "6 min",
    publishDate: "2026-05-04",
    excerpt: "Mevsim, yağmur ve sıcak hazırlığı",
  },
  {
    id: "toll-roads",
    title: "Tayland'da Otoyollar ve Geçiş Ücretleri",
    category: "Pratik",
    readTime: "4 min",
    publishDate: "2026-05-02",
    excerpt: "Otoyol sistemi ve ücretler",
  },
  {
    id: "petrol-vs-diesel",
    title: "Motosiklet Seçerken: Benzin vs Dizel",
    category: "Pratik",
    readTime: "5 min",
    publishDate: "2026-04-30",
    excerpt: "Yakıt tipi seçimi ve verimlilik",
  },
  {
    id: "night-riding",
    title: "Phuket'te Gece Sürüşü - Güvenlik İpuçları",
    category: "Güvenlik",
    readTime: "6 min",
    publishDate: "2026-04-28",
    excerpt: "Gece sürüşü teknikleri ve tehlikeleri",
  },
  {
    id: "monsoon-riding",
    title: "Yağmur Sezonunda Phuket'te Sürüş",
    category: "İpuçları",
    readTime: "7 min",
    publishDate: "2026-04-26",
    excerpt: "Yağmurda güvenli sürüş teknikleri",
  },
  {
    id: "temple-visits",
    title: "Tayland Tapınaklarında Motosikletçi Kuralları",
    category: "Kültür",
    readTime: "4 min",
    publishDate: "2026-04-24",
    excerpt: "Tapınak ziyaretinde dikkat edilmesi gerekenler",
  },
  {
    id: "local-restaurants",
    title: "Phuket'te Yerel Yemek Rehberi - Motosikletçi Tipsiz",
    category: "Pratik",
    readTime: "8 min",
    publishDate: "2026-04-22",
    excerpt: "Güvenli ve lezzetli yerel restaurants",
  },
  {
    id: "photography-spots",
    title: "Motosikletle Fotoğraf Çekme - Phuket'in Fotojenikleri",
    category: "İpuçları",
    readTime: "6 min",
    publishDate: "2026-04-20",
    excerpt: "En güzel fotoğraf noktaları ve teknikler",
  },
  // MOTORCYCLE SELECTION (8)
  {
    id: "best-scooter",
    title: "Phuket'te Hangi Scooter Seçmeliyim?",
    category: "Motosikletler",
    readTime: "9 min",
    publishDate: "2026-04-18",
    excerpt: "Click vs ADV vs Forza - karşılaştırma",
  },
  {
    id: "click-vs-adv",
    title: "Click 160 vs ADV 160 - Detaylı Karşılaştırma",
    category: "Motosikletler",
    readTime: "7 min",
    publishDate: "2026-04-16",
    excerpt: "İki populer modelin derinlemesine karşılaştırması",
  },
  {
    id: "couples-motorcycle",
    title: "Çiftler İçin Hangi Motosiklet Uygun?",
    category: "Motosikletler",
    readTime: "6 min",
    publishDate: "2026-04-14",
    excerpt: "İki kişilik sürüşte confort ve güvenlik",
  },
  {
    id: "solo-traveler",
    title: "Solo Seyahatçılar İçin Motosiklet Seçimi",
    category: "Motosikletler",
    readTime: "6 min",
    publishDate: "2026-04-12",
    excerpt: "Tek başına sürüşte ideal model",
  },
  {
    id: "beginner-bike",
    title: "İlk Kez Kiralayan Başlangıçlar İçin Motosiklet",
    category: "Motosikletler",
    readTime: "5 min",
    publishDate: "2026-04-10",
    excerpt: "Anfänger-freundliche modeller ve tipps",
  },
  {
    id: "long-distance-bike",
    title: "Uzun Mesafe Sürüşü İçin En İyi Motosiklet",
    category: "Motosikletler",
    readTime: "7 min",
    publishDate: "2026-04-08",
    excerpt: "Konfort ve verimlilik öncelikleri",
  },
  {
    id: "automatic-vs-manual",
    title: "Otomatikte vs Manuel - Phuket'te Hangi Seçmeli?",
    category: "Motosikletler",
    readTime: "6 min",
    publishDate: "2026-04-06",
    excerpt: "Her birinin avantaj ve dezavantajları",
  },
  {
    id: "helmet-types",
    title: "Motosiklet Kaskı Seçimi - Türleri ve Fiyatları",
    category: "Donanım",
    readTime: "5 min",
    publishDate: "2026-04-04",
    excerpt: "Kask türleri ve güvenlik sertifikaları",
  },
  // REGIONAL GUIDES (10)
  {
    id: "complete-phuket",
    title: "Phuket'e Gideceklere Tam Rehber",
    category: "Rehber",
    readTime: "15 min",
    publishDate: "2026-04-02",
    excerpt: "Phuket'in her köşesi motosikletçi perspektifinden",
  },
  {
    id: "complete-krabi",
    title: "Krabi'yi Motosikletçi Gözüyle Keşfet",
    category: "Rehber",
    readTime: "12 min",
    publishDate: "2026-03-31",
    excerpt: "Krabi'nin tüm highlight'ları",
  },
  {
    id: "complete-khao-sok",
    title: "Khao Sok National Park - Macera Rehberi",
    category: "Rehber",
    readTime: "10 min",
    publishDate: "2026-03-29",
    excerpt: "Orman ve doğa sürüşü deneyimi",
  },
  {
    id: "complete-phang-nga",
    title: "Phang Nga Körfezi - Kayalık Masalı",
    category: "Rehber",
    readTime: "11 min",
    publishDate: "2026-03-27",
    excerpt: "Phang Nga'nın eşsiz coğrafyası",
  },
  {
    id: "phuket-town",
    title: "Phuket Şehrinde Neyi Görmeli?",
    category: "Kültür",
    readTime: "7 min",
    publishDate: "2026-03-25",
    excerpt: "Eski ve yeni Phuket karşılaştırması",
  },
  {
    id: "patong-guide",
    title: "Patong Plajı - Turizm Merkezinin İçinde",
    category: "Rehber",
    readTime: "8 min",
    publishDate: "2026-03-23",
    excerpt: "Patong'un gece ve gündüz hayatı",
  },
  {
    id: "kata-karon",
    title: "Kata ve Karon Plajları - Sakin Alternatif",
    category: "Rehber",
    readTime: "7 min",
    publishDate: "2026-03-21",
    excerpt: "Patong'dan daha sakin plajlar",
  },
  {
    id: "rawai-guide",
    title: "Rawai - Yerel Plaj ve Deniz Yemekleri",
    category: "Rehber",
    readTime: "6 min",
    publishDate: "2026-03-19",
    excerpt: "Phuket'in güney ucundaki gizli cevher",
  },
  {
    id: "bang-tao",
    title: "Bang Tao - Lüks Resort Plajı",
    category: "Rehber",
    readTime: "6 min",
    publishDate: "2026-03-17",
    excerpt: "Premium plaj ve resort deneyimi",
  },
  {
    id: "old-phuket-town",
    title: "Phuket'in Eski Şehri - Sino-Portekiz Mimarisi",
    category: "Kültür",
    readTime: "7 min",
    publishDate: "2026-03-15",
    excerpt: "Tarihsel Phuket'i keşfet",
  },
  // COMPARISON ARTICLES (8)
  {
    id: "scooter-vs-motorcycle",
    title: "Scooter vs Motosiklet - Phuket'te Hangisini Seçmeli?",
    category: "Karşılaştırma",
    readTime: "6 min",
    publishDate: "2026-03-13",
    excerpt: "Otomatik scooter vs manuel motosiklet",
  },
  {
    id: "rental-vs-buying",
    title: "Kiralama vs Satın Alma - Tayland'da Uzun Süreli",
    category: "Karşılaştırma",
    readTime: "7 min",
    publishDate: "2026-03-11",
    excerpt: "Uzun müddete ne yapmak daha ekonomik?",
  },
  {
    id: "tourist-vs-local",
    title: "Turist Fiyatları vs Yerel Fiyatlar - Anlaşma Taktikleri",
    category: "Karşılaştırma",
    readTime: "5 min",
    publishDate: "2026-03-09",
    excerpt: "Tayland'da pazarlık nasıl yapılır?",
  },
  {
    id: "high-vs-low-season",
    title: "Yüksek Sezon vs Düşük Sezon - Zaman Seçimi",
    category: "Karşılaştırma",
    readTime: "6 min",
    publishDate: "2026-03-07",
    excerpt: "Hangi zaman daha iyi?",
  },
  {
    id: "package-vs-diy",
    title: "Paket Turlar vs Kendi Kendinize - Hangisi Daha İyi?",
    category: "Karşılaştırma",
    readTime: "7 min",
    publishDate: "2026-03-05",
    excerpt: "Rehbersiz vs rehberli sürüş",
  },
  {
    id: "group-vs-solo",
    title: "Grup Sürüşü vs Solo Sürüş - Avantajlar",
    category: "Karşılaştırma",
    readTime: "5 min",
    publishDate: "2026-03-03",
    excerpt: "Hangisi daha eğlenceli?",
  },
  {
    id: "daytrip-vs-multiday",
    title: "Günübirlik Tur vs Multi-Gün Sürüş",
    category: "Karşılaştırma",
    readTime: "6 min",
    publishDate: "2026-03-01",
    excerpt: "Sürüş süresi planlama",
  },
  {
    id: "backpacker-vs-luxury",
    title: "Backpacker Sürüşü vs Lüks Motosiklet Turu",
    category: "Karşılaştırma",
    readTime: "6 min",
    publishDate: "2026-02-27",
    excerpt: "Bütçe seçenekleri",
  },
  // EXPERIENCE STORIES (8)
  {
    id: "beginner-pov",
    title: "İlk Kez Phuket'te Motosiklet Kiralayan Başlangıçlar",
    category: "Deneyim",
    readTime: "8 min",
    publishDate: "2026-02-25",
    excerpt: "Başlangıçların başarı ve hatası hikaye",
  },
  {
    id: "worst-mistakes",
    title: "Phuket'te Motosiklet Kiralayan Yaptığım En Kötü Hatalar",
    category: "Deneyim",
    readTime: "7 min",
    publishDate: "2026-02-23",
    excerpt: "Uyarı ve öğrenme hikayeleri",
  },
  {
    id: "sunset-spots",
    title: "Motosikletle Gördüğüm En Güzel Günbatışılar",
    category: "Deneyim",
    readTime: "6 min",
    publishDate: "2026-02-21",
    excerpt: "Fotoğraflar ve anılar",
  },
  {
    id: "solo-female",
    title: "Kadın Sürücü - Solo Kadın Seyahati Phuket'te",
    category: "Deneyim",
    readTime: "9 min",
    publishDate: "2026-02-19",
    excerpt: "Güvenlik ve bağımsızlık",
  },
  {
    id: "first-time-riding",
    title: "İlk Kez Tayland'da Motosiklet Sürüşü - Kalp Çarpması",
    category: "Deneyim",
    readTime: "8 min",
    publishDate: "2026-02-17",
    excerpt: "Trafik şoku ve alışma",
  },
  {
    id: "phuket-to-krabi",
    title: "Phuket'ten Krabi'ye Motosikletçi Macerası",
    category: "Deneyim",
    readTime: "10 min",
    publishDate: "2026-02-15",
    excerpt: "Multi-günlük rota deneyimi",
  },
  {
    id: "budget-trip",
    title: "100 USD Bütçeyle Phuket'te 5 Gün",
    category: "Deneyim",
    readTime: "7 min",
    publishDate: "2026-02-13",
    excerpt: "Ekonomik seyahat tipsiz",
  },
  {
    id: "luxury-tour",
    title: "Phuket'te Lüks Motosiklet Turu - VIP Deneyim",
    category: "Deneyim",
    readTime: "8 min",
    publishDate: "2026-02-11",
    excerpt: "Premium kiralama hizmetleri",
  },
];

export const getArticleById = (id: string) => {
  return TRAVEL_GUIDE_ARTICLES.find((article) => article.id === id);
};

export const getArticlesByCategory = (category: string) => {
  return TRAVEL_GUIDE_ARTICLES.filter((article) => article.category === category);
};

export const getAllCategories = () => {
  const categories = new Map<string, number>();
  TRAVEL_GUIDE_ARTICLES.forEach((article) => {
    categories.set(article.category, (categories.get(article.category) || 0) + 1);
  });
  return Array.from(categories.entries()).map(([name, count]) => ({ name, count }));
};
