/** Gezilecek yer çekicilik puanı — 10 en yüksek, aşağı doğru */
export const DESTINATION_APPEAL: Record<string, number> = {
  "big-buddha": 10,
  "james-bond-island": 10,
  "samet-nangshe": 10,
  "koh-phi-phi": 10,
  "similan-islands": 10,
  "promthep-cape": 9,
  "phang-nga-bay": 9,
  "railay-beach": 9,
  "emerald-pool": 9,
  "cheow-lan-lake": 9,
  "banana-beach": 9,
  "freedom-beach": 9,
  "karon-viewpoint": 8,
  "windmill-viewpoint": 8,
  "tiger-cave-krabi": 8,
  "coral-island": 8,
  "bamboo-island": 8,
  "ao-nang": 8,
  "paradise-beach": 8,
  "kata-beach": 8,
  "nai-harn-beach": 8,
  "hot-springs": 7,
  "khao-sok-national-park": 7,
  "monkey-hill": 7,
  "rawai-beach": 7,
  "surin-beach": 7,
  "bang-tao-beach": 7,
  "kamala-beach": 7,
  "old-phuket-town": 7,
  "wat-chalong": 7,
  "khao-lak": 7,
  "phang-nga-cave": 7,
  "monkey-beach": 7,
  "koh-naka-island": 7,
  "lanta-island": 7,
  "patong-beach": 6,
  "krabi-town": 6,
  "radar-hill-viewpoint": 6,
  "sirinat-national-park": 6,
  "bang-tao-temple": 6,
  "soi-dog-foundation": 6,
  "ton-prai-waterfall": 6,
  "bang-pae-waterfall": 6,
  "khao-yai-viewpoint": 6,
  "phrom-thep-cape-lighthouse": 6,
  "thalang-viewpoint": 6,
  "phuket-aquarium": 5,
  "phuket-fantasea": 5,
  "bang-pae-elephant-sanctuary": 5,
  "patong-fish-market": 5,
  "three-pagodas-pass": 5,
  "sticky-waterfall": 5,
  "erawan-national-park": 5,
  "mae-sa-waterfall": 5,
  "monkey-cave": 7,
  "khao-rang": 7,
  "mai-khao-plane-spot": 8,
  "bangla-road": 6,
  "donsak-samui-ferry": 8,
};

export function getAppealScore(slug: string): number {
  return DESTINATION_APPEAL[slug] ?? 7;
}
