import type { MotorcycleRoute } from "@/lib/routes-types";
import { buildStop, finalizeRoute, routeHeroImage } from "@/lib/multi-route-helpers";

export { finalizeRoute } from "@/lib/multi-route-helpers";

/** Çok günlük turlar — ayrı program sayfalarında */
export const MULTI_DAY_ROUTES: MotorcycleRoute[] = [
  finalizeRoute({
    id: "phang-nga-scenic",
    name: "Phang Nga 2 Günlük Tur",
    tagline: "Körfez, mağara ve konaklamalı keşif",
    difficulty: "Kolay",
    elevation: "~300 m",
    bestTime: "Cuma çıkış veya hafta sonu",
    image: routeHeroImage("samet-nangshe", ""),
    description:
      "Samet Nangshe'de geceleyerek Phang Nga körfezini iki günde keşfedin. 1. gün viewpoint ve tekne turu; 2. gün Maymun Mağarası ve dönüş. Detaylı günlük program rota sayfasında.",
    highlights: "Samet Nangshe, Maymun Mağarası, James Bond, Koh Panyee",
    recommendedBike: "Honda ADV 160 / Forza 350",
    startPoint: "Patong Beach Roundabout",
    parkingInfo: "Otel ve iskele otoparkları",
    fuelEstimate: "~8 L · 350 THB",
    totalDriveKm: 180,
    stops: [
      buildStop({ order: 1, name: "Samet Nangshe Viewpoint", description: "Gün batımı ve konaklama bölgesi.", driveKm: 35, driveMin: 50, visitMin: 90, destinationSlug: "samet-nangshe" }),
      buildStop({ order: 2, name: "Konaklama (Samet Nangshe / Phang Nga)", description: "Boutique otel veya Phang Nga Town.", driveKm: 5, driveMin: 10, visitMin: 720 }),
      buildStop({ order: 3, name: "Maymun Mağarası", description: "2. gün sabah mağara tapınağı.", driveKm: 25, driveMin: 35, visitMin: 45, destinationSlug: "monkey-cave" }),
      buildStop({ order: 4, name: "James Bond & Körfez (tekne)", description: "Surakul İskelesi'nden tekne turu.", driveKm: 20, driveMin: 30, visitMin: 180, destinationSlug: "james-bond-island", access: "boat" }),
      buildStop({ order: 5, name: "Patong — Dönüş", description: "402 ile güneye.", driveKm: 90, driveMin: 110, visitMin: 0 }),
    ],
    safetyTips: [
      { icon: "🏨", title: "Rezervasyon", text: "Hafta sonu Samet Nangshe otelleri doluyor." },
      { icon: "🌅", title: "Gün doğumu", text: "Viewpoint için 05:30 kalkış planlayın." },
      { icon: "⛵", title: "Tekne", text: "2. gün sabah erken tekne turu daha sakin." },
    ],
  }),
  finalizeRoute({
    id: "khao-sok",
    name: "Khao Sok 2 Günlük Macera",
    tagline: "Orman bungalov + Cheow Lan Gölü",
    difficulty: "Zor",
    elevation: "~800 m",
    bestTime: "Kuru sezon; yağmurda dikkat",
    image: routeHeroImage("khao-sok-national-park", ""),
    description: "Khao Sok orman yolu ve Cheow Lan göl turu. 1. gece köy bungalovu veya floating raft; 2. gün göl turu ve dönüş.",
    highlights: "Khao Sok, Cheow Lan Lake, Orman yolu",
    recommendedBike: "Honda ADV 350 / Forza 350",
    startPoint: "Patong Beach Roundabout",
    parkingInfo: "Park girişi ve baraj otoparkı",
    fuelEstimate: "~10 L · 450 THB",
    totalDriveKm: 260,
    stops: [
      buildStop({ order: 1, name: "Khao Sok Köyü", description: "Milli park girişi; 1. gece konaklama.", driveKm: 130, driveMin: 150, visitMin: 120, destinationSlug: "khao-sok-national-park" }),
      buildStop({ order: 2, name: "Konaklama", description: "Orman bungalov veya raft house.", driveKm: 0, driveMin: 0, visitMin: 720 }),
      buildStop({ order: 3, name: "Cheow Lan Gölü", description: "Baraj iskelesi tekne turu.", driveKm: 15, driveMin: 30, visitMin: 180, destinationSlug: "cheow-lan-lake", access: "boat" }),
      buildStop({ order: 4, name: "Patong — Dönüş", description: "Aynı yoldan ~130 km.", driveKm: 130, driveMin: 150, visitMin: 0 }),
    ],
    safetyTips: [
      { icon: "🌧️", title: "Yağmur", text: "Ormanda ani sağanak sık." },
      { icon: "🛞", title: "Yol", text: "Dar virajlar; gece sürüşünden kaçının." },
      { icon: "🧭", title: "GPS", text: "Offline harita şart." },
    ],
  }),
  finalizeRoute({
    id: "krabi-day",
    name: "Krabi 5 Günlük Tur",
    tagline: "Tiger Cave, Emerald Pool, Railay — konaklamalı",
    difficulty: "Orta",
    elevation: "~700 m",
    bestTime: "Kuru sezon; sabah erken sürüş",
    image: routeHeroImage("emerald-pool", ""),
    description: "Phuket'ten Krabi'ye 5 günlük motosiklet turu. Her gün farklı durak; Ao Nang veya Krabi Town'da konaklama. Günlük program detay sayfada.",
    highlights: "Tiger Cave, Emerald Pool, Hot Springs, Railay, Ao Nang",
    recommendedBike: "Honda ADV 160 / Forza 350",
    startPoint: "Patong Beach Roundabout",
    parkingInfo: "Otellerde moto park genelde ücretsiz",
    fuelEstimate: "~25 L toplam · 1000+ THB",
    totalDriveKm: 420,
    stops: [
      buildStop({ order: 1, name: "Ao Nang (1. gece)", description: "Gidiş günü konaklama.", driveKm: 160, driveMin: 180, visitMin: 60, destinationSlug: "ao-nang" }),
      buildStop({ order: 2, name: "Tiger Cave", description: "2. gün 1260 basamak.", driveKm: 15, driveMin: 20, visitMin: 120, destinationSlug: "tiger-cave-krabi" }),
      buildStop({ order: 3, name: "Emerald Pool", description: "Turkuaz doğal havuz.", driveKm: 25, driveMin: 35, visitMin: 90, destinationSlug: "emerald-pool" }),
      buildStop({ order: 4, name: "Hot Springs", description: "Khlong Thom sıcak kaynakları.", driveKm: 20, driveMin: 30, visitMin: 90, destinationSlug: "hot-springs" }),
      buildStop({ order: 5, name: "Railay (tekne)", description: "Longtail ile kireçtaşı plajı.", driveKm: 8, driveMin: 15, visitMin: 180, destinationSlug: "railay-beach", access: "boat" }),
      buildStop({ order: 6, name: "Patong — Dönüş", description: "5. gün ~160 km.", driveKm: 160, driveMin: 180, visitMin: 0 }),
    ],
    safetyTips: [
      { icon: "🌧️", title: "Yağmur", text: "Yağmurluk taşıyın." },
      { icon: "🏨", title: "Konaklama", text: "Ao Nang'da önceden rezervasyon." },
      { icon: "⛵", title: "Railay", text: "Moto Ao Nang'da park; çanta longtail'e." },
    ],
  }),
  finalizeRoute({
    id: "similan-islands",
    name: "Similan Adaları (2 gün)",
    tagline: "Khao Lak konaklama + tekne turu",
    difficulty: "Orta",
    elevation: "0 m",
    bestTime: "Kasım–Nisan (açık sezon)",
    image: routeHeroImage("similan-islands", ""),
    description: "Patong'dan Khao Lak'a motosiklet; 2. gün sabah Similan tekne turu. Dalış/şnorkel için rezervasyon şart.",
    highlights: "Similan, Mercan resifleri, Khao Lak",
    recommendedBike: "Honda ADV 160 / Forza 350",
    startPoint: "Patong Beach Roundabout",
    parkingInfo: "Thap Lamu / tur operatörü otoparkı",
    fuelEstimate: "~12 L · 500 THB + tur",
    totalDriveKm: 220,
    stops: [
      buildStop({ order: 1, name: "Khao Lak / Thap Lamu", description: "1. gece konaklama.", driveKm: 110, driveMin: 130, visitMin: 60, destinationSlug: "khao-lak" }),
      buildStop({ order: 2, name: "Similan (tekne)", description: "Sabah 07:30 kalkışlı tur.", driveKm: 25, driveMin: 30, visitMin: 480, destinationSlug: "similan-islands", access: "boat" }),
      buildStop({ order: 3, name: "Patong — Dönüş", description: "2. gün akşam veya 3. gün sabah.", driveKm: 110, driveMin: 130, visitMin: 0 }),
    ],
    safetyTips: [
      { icon: "🤿", title: "Dalış", text: "PADI sertifikası gerekebilir." },
      { icon: "⏰", title: "Erken", text: "Tekne sabah erken kalkar." },
      { icon: "🌊", title: "Deniz", text: "Mevsim dışı tur iptal olabilir." },
    ],
  }),
  finalizeRoute({
    id: "samet-nangshe-2day",
    name: "Samet Nangshe 2 Günlük",
    tagline: "Körfez manzarasında konaklama",
    difficulty: "Kolay",
    elevation: "~350 m",
    bestTime: "Cuma akşamı veya cumartesi sabah",
    image: routeHeroImage("samet-nangshe", ""),
    description: "Viewpoint çevresinde bir gece; gün doğumu ve Phang Nga keşfi. Minimal sürüş, maksimum manzara.",
    highlights: "Samet Nangshe, Gün doğumu, Phang Nga",
    recommendedBike: "Honda ADV 160",
    startPoint: "Patong Beach Roundabout",
    parkingInfo: "Otel otoparkı ücretsiz",
    fuelEstimate: "~4 L · 180 THB",
    totalDriveKm: 80,
    stops: [
      buildStop({ order: 1, name: "Samet Nangshe Viewpoint", description: "1. gün varış ve gün batımı.", driveKm: 35, driveMin: 50, visitMin: 120, destinationSlug: "samet-nangshe" }),
      buildStop({ order: 2, name: "Konaklama", description: "Viewpoint yakını otel / çadır.", driveKm: 2, driveMin: 5, visitMin: 720 }),
      buildStop({ order: 3, name: "Gün doğumu & dönüş", description: "2. gün sabah viewpoint; öğleden sonra Patong.", driveKm: 40, driveMin: 55, visitMin: 90, destinationSlug: "samet-nangshe" }),
    ],
    safetyTips: [
      { icon: "🌅", title: "Gün doğumu", text: "05:30–06:00 arası en iyi ışık." },
      { icon: "🏨", title: "Rezervasyon", text: "Hafta sonu doluluk yüksek." },
      { icon: "🔦", title: "Fener", text: "Sabah karanlık yürüyüş için el feneri." },
    ],
  }),
];
