export interface RouteStop {
  order: number;
  name: string;
  distance: string;
  duration: string;
  description: string;
}

export interface SafetyTip {
  icon: string;
  title: string;
  text: string;
}

export interface MotorcycleRoute {
  id: string;
  name: string;
  description: string;
  distance: string;
  duration: string;
  difficulty: "Kolay" | "Orta" | "Zor";
  highlights: string;
  recommendedBike: string;
  tagline: string;
  image: string;
  bestTime: string;
  elevation: string;
  startPoint: string;
  parkingInfo: string;
  stops: RouteStop[];
  safetyTips: SafetyTip[];
}

export const MOTORCYCLE_ROUTES: MotorcycleRoute[] = [
  // TIER-1 HIGH-INTENT ROUTES
  {
    id: "south-phuket",
    name: "Güney Phuket Loop",
    tagline: "Phuket'in en ikonik rotası - Big Buddha → Promthep Cape",
    difficulty: "Kolay",
    distance: "85 km",
    duration: "4 saat",
    elevation: "500 m",
    bestTime: "Sabah erken (08:00-11:00) veya akşam (16:00-18:30)",
    image: "https://images.pexels.com/photos/699122/pexels-photo-699122.jpeg?w=1200&q=90",
    description: "Phuket'in güney tarafındaki en ikonik noktaları bir rotada keşfedin. 45 metre yüksekliğindeki Big Buddha'dan başlayıp, batılı sanatçıların tercih ettiği Promthep Cape'de günbatışını izlemekle biten bu rota, Phuket'in en popüler fotoğraf lokasyonlarını içerir. Yol baştan sona muhteşem manzaralarla dolu ve başlamak için en iyi rota. Bu rota özellikle ilk kez Phuket'e gelen ziyaretçilere ideal çünkü tüm ana attraksiyonları içerir ve aynı zamanda yerel yaşamın tadını vermeyi başarır. Patong Beach'ten başladığınızda, uydu yolunu takip ederek Phuket'in en yüksek noktasına ulaşırsınız. Big Buddha'ya vardığınızda, 45 metre yüksekliğindeki bu ikonik heykelin cazibesine kapılacaksınız. Fotoğraflar için en iyi açı sabah ışığında, doğu tarafından gelen güneş arka plana mükemmel çerçeve oluşturur. Buradan yaklaşık 25 kilometre uzakta olan Promthep Cape'ye gitmek son derece kolaydır ve yol boyunca Phuket'in sahil köylerini görebilirsiniz. Windmill Viewpoint'te durma imkanı var - bu noktada Phuket'in panoramik manzarası yer almaktadır. Karon Viewpoint'te durup, üç güzel koyun (Karon, Kata, Big Buddha Beach) aynı anda görmek mümkündür. Benzin tüketimi yaklaşık 7 litre olup, toplam maliyet yaklaşık 300-400 THB'dir. Zorluk seviyesi çok düşüktür, çünkü yollar iyi bakımlı ve işaretlidir. Sezon dışında bu rotayı takip etmek daha sakin bir deneyim sunacaktır.",
    highlights: "Big Buddha, Promthep Cape, Windmill Viewpoint, Karon Viewpoint, Rawai Beach",
    recommendedBike: "Honda Click 160 / ADV 160",
    startPoint: "Patong Beach Roundabout",
    parkingInfo: "Tüm durakların otopark alanları var",
    stops: [
      {
        order: 1,
        name: "Big Buddha",
        distance: "Başlangıç",
        duration: "30 dakika",
        description: "Phuket'in sembolü 45 metre yüksekliğindeki Buda heykeli.",
      },
      {
        order: 2,
        name: "Promthep Cape",
        distance: "25 km",
        duration: "20 dakika sürüş",
        description: "Phuket'in en güzel günbatışı noktası.",
      },
      {
        order: 3,
        name: "Windmill Viewpoint",
        distance: "18 km",
        duration: "15 dakika sürüş",
        description: "Phuket'in manzarasının en güzel açısı.",
      },
      {
        order: 4,
        name: "Karon Viewpoint",
        distance: "22 km",
        duration: "20 dakika sürüş",
        description: "Üç koyun manzarasını aynı anda görebileceğiniz ünlü fotoğraf noktası.",
      },
    ],
    safetyTips: [
      {
        icon: "⚠️",
        title: "Hız Kontrolü",
        text: "Dönüşlü yollar kazaya neden olabilir. Hızı düşürün.",
      },
      {
        icon: "🌡️",
        title: "Güneş Koruması",
        text: "SPF koruyucu güneş kremi kullanın.",
      },
      {
        icon: "⛽",
        title: "Yakıt Doldurma",
        text: "Patong'dan çıkmadan yakıt doldurın.",
      },
    ],
  },
  {
    id: "krabi-day",
    name: "Krabi Günü",
    tagline: "Mağaralar, sıcak kaynaklar ve Railay",
    difficulty: "Orta",
    distance: "130 km",
    duration: "7–8 saat",
    elevation: "700 m",
    bestTime: "Sabah 08:00",
    image: "https://images.pexels.com/photos/1619317/pexels-photo-1619317.jpeg?w=1200&q=90",
    description: "Phuket'ten Krabi'ye uzanan muhteşem rota, doğanın en güzel ayetlerini sergileyen macera rotasıdır. Kavernlı mağaralar, kristal berrak sıcak kaynaklar ve yoğun yeşil cungeller bu rotanın ana karakteristikleridir. Phang Nga yolu üzerinden gideceğiniz bu 120 kilometrelik tur yaklaşık 6 saat sürer ve zorluk seviyesi orta düzeydedir. Patong Beach Roundabout'tan başladığınızda, ilk olarak Phang Nga vilayetine gireceğiniz ve dönüşlü dağ yollarını takip edeceksiniz. Tiger Cave Temple (Wat Tham Suea) 80 kilometre uzakta yer almakta ve şamanist inançların merkezi olmuştur. Mağara tapınağının içerisinde 1,260 basamak tırmanmamız gerekiyorsa da, bunun yerine sadece 300 metre yürüyüş yaparak bu kutsal mekanı görebilirsiniz. Emerald Pool, doğal jeotermal etkinlikten ortaya çıkmış ve açık yeşil rengiyle dikkat çeken bir hazıreydir. Burada yüzmek güvenlidir ancak sıcak su nedeniyle dikkatli olmalısınız. Hot Springs ise doğal çamur banyosu ve mineral açısından zengin sıcak sular sunmaktadır. Sıcak kaynaklarda batıktan sonra cildini tazeleyecek hissedersiniz. Benzin tüketimi yaklaşık 9-10 litre ve maliyeti 400-500 THB'dir. En iyi zaman sabah 8:00'dir çünkü turist kalabalığını önlemiş olursunuz. Yağmur riskine karşı her zaman hazırlanmalı ve harita bulundurmalısınız.",
    highlights: "Tiger Cave, Emerald Pool, Hot Springs, Ao Nang, Railay Plajı",
    recommendedBike: "Honda ADV 160 / Forza 350",
    startPoint: "Patong Beach Roundabout",
    parkingInfo: "Tüm seviyelerde güvenli otopark var",
    stops: [
      {
        order: 1,
        name: "Phuket Boundary",
        distance: "0 km",
        duration: "0 dakika",
        description: "Patong'dan Phang Nga yoluna başlayın.",
      },
      {
        order: 2,
        name: "Tiger Cave (Wat Tham Suea)",
        distance: "80 km",
        duration: "90 dakika sürüş",
        description: "Mağara tapınağı ve tırmanılabilir merdivenler.",
      },
      {
        order: 3,
        name: "Emerald Pool",
        distance: "95 km",
        duration: "30 dakika sürüş",
        description: "Kristal berrak turkuaz havuz, şnorkelli dalış.",
      },
      {
        order: 4,
        name: "Hot Springs",
        distance: "105 km",
        duration: "30 dakika sürüş",
        description: "Doğal sıcak kaynaklar ve çamur banyosu.",
      },
      {
        order: 5,
        name: "Ao Nang İskelesi → Railay Plajı",
        distance: "115 km",
        duration: "20 dakika sürüş + 10 dk longtail",
        description: "Motoru Ao Nang'da park edin, iskeleden longtail tekneyle Railay'e geçin (~100 THB). Kireçtaşı kayalıkları arasındaki bu plajı görmeden Krabi'den dönmek olmaz.",
      },
    ],
    safetyTips: [
      {
        icon: "🌧️",
        title: "Yağmur Hazırlığı",
        text: "Ani yağmurlar olabilir. Yağmurluk yanınızda taşıyın.",
      },
      {
        icon: "🦗",
        title: "Böcek Koruması",
        text: "Böcek kovucu sprey alın.",
      },
      {
        icon: "🛣️",
        title: "Yol Durumu",
        text: "Dönüşler tehlikeli olabilir.",
      },
    ],
  },
  {
    id: "tiger-cave",
    name: "Tiger Cave Özel Turu",
    tagline: "Krabi'nin en ünlü tapınağı - Mağara & Merdivenleri",
    difficulty: "Orta",
    distance: "95 km",
    duration: "5 saat",
    elevation: "600 m",
    bestTime: "Sabah 8-11 AM (kalabalık olmadan)",
    image: "https://images.pexels.com/photos/4254129/pexels-photo-4254129.jpeg?w=1200&q=90",
    description: "Tiger Cave Temple'e gitmek ve 1,260 adımı tırmanmak Tayland'da yapılması gereken şeylerden biridir. Krabi vilayetinin en ikonik tapınağı olan bu yer, Budist inancının derinliğini anlamanızı sağlar. Rotanız 95 kilometre uzunluğunda olup 5 saat sürecektir. Patong Beach'ten çıkarak Phang Nga üzerinden Krabi yoluna gireceksiniz. Yol boyunca ormanlık alanlar ve dağ köyleri göreceksiniz. Tiger Cave'nin adı, bu mağaraya bir zamanlar ticiler tarafından tapınması inancından gelmektedir. Tapınağa vardığınızda, kutsal hava hissedecek ve yerel rahiblerin yardımıyla mekanı tanıyabileceksiniz. Merdivenler ilk 300 metresi oldukça kolay ve geniş basamaklar içerir. Ortasında dinlenme alanları vardır ve İnsan doğası gereği, acele etmelisiniz çünkü merdivenin üstündeki sıcaklık çok fazla olabilir. Tabakası olanlar daha hızlı tırmanabilirler, ancak fiziki aktiviteye alışık olmayan kişiler 45-60 dakika içinde tepeye ulaşabilirler. Tepe arasında bir Buddha heykeli ve moderin tapınak binaları bulunmaktadır. İniş daha stresli olabilir, bu nedenle dengeyi korumalı ve acele etmemelisiniz. Benzin harcaması yaklaşık 8 litre ve maliyet 350-450 THB'dir.",
    highlights: "Tiger Cave, 1260 Steps, Mağara Tapınağı, Buddha Heykelleri, Panoramik View",
    recommendedBike: "Honda ADV 160 / Forza 350",
    startPoint: "Patong Beach Roundabout",
    parkingInfo: "Bol otopark, giriş 20 THB",
    stops: [
      {
        order: 1,
        name: "Patong'dan Çıkış",
        distance: "0 km",
        duration: "0 dakika",
        description: "Patong Beach Roundabout'tan başlayın, Phang Nga yoluna gidin.",
      },
      {
        order: 2,
        name: "Tiger Cave Parking",
        distance: "80 km",
        duration: "90 dakika sürüş (Phang Nga üzerinden)",
        description: "Krabi'ye yaklaştıkça tapınak işaretleri göreceksiniz. Otopark alanında motosikleti bırakın.",
      },
      {
        order: 3,
        name: "Merdiven Tırmanışı",
        distance: "0 km",
        duration: "60 dakika (30 dakika yukarı, 15 dakika indir)",
        description: "1260 adımlık merdivenler var. Başında saatler var, kendi hızınızda gidin. Öğle güneşi çok sıcak olabilir.",
      },
      {
        order: 4,
        name: "Patong'a Geri Dönüş",
        distance: "80 km",
        duration: "90 dakika sürüş",
        description: "Aynı yoldan geri dönün. Akşam yemeği için Patong'a varacaksınız.",
      },
    ],
    safetyTips: [
      {
        icon: "👟",
        title: "Uygun Ayakkabı",
        text: "İyi kaymayan spor ayakkabısı giy.",
      },
      {
        icon: "💧",
        title: "Su İçme",
        text: "Bol su taşı, tırmanış sırasında hidrate ol.",
      },
      {
        icon: "🕐",
        title: "Erken Başla",
        text: "Sabah erken başlayıp öğle saati inmeye çalış.",
      },
    ],
  },
  {
    id: "phuket-sunset",
    name: "Phuket Sunset Route",
    tagline: "Samet Nangshe ve Promthep Cape günbatışı",
    difficulty: "Kolay",
    distance: "78 km",
    duration: "3.5 saat",
    elevation: "400 m",
    bestTime: "14:00-18:00",
    image: "https://images.pexels.com/photos/1181690/pexels-photo-1181690.jpeg?w=1200&q=90",
    description: "Phuket'in en iyi günbatışı noktalarını sürüş yaparak görmek, fotoğrafçılar ve doğa severler için ideal bir rotadır. Bu 78 kilometrelik tur 3,5 saatte tamamlanabilir ve zor seviyesi çok düşüktür. Samet Nangshe Viewpoint ile başlarsınız; burası Phuket'in en ünlü manzara noktalarından biridir ve üç koyunun eş zamanlı görülmesini sağlar. Bu yer özellikle Instagram fotoğrafları için dikkat çekmektedir ve her zaman turist doluyken akşam saatleri daha sakin olabilir. Promthep Cape, Phuket'in en güzel günbatışı konumudur ve batı tarafını tamamen kaplayan gün iniş manzarası sunmaktadır. Buraya yaklaşık 17:00-18:00 arası gelmek en iyi zamandır. Karon Viewpoint'ten başka bir açıdan fotoğraflar çekebilir ve yerleşim yeri gece ışıklarının tadını verebilirsiniz. Toplam rota boyunca araçlı sürüşte 1.5 saat, durma ve fotoğraf çekmede ise 2 saat harcayacaksınız. Benzin tüketimi 5-6 litre olup maliyet 250-300 THB'dir. Işık nedeniyle gece sürüşüne dönüşebileceği için hızını kontrol edin ve işıklarınızı açık tutun.",
    highlights: "Samet Nangshe, Promthep Cape, Karon Viewpoint, Sunset Photography",
    recommendedBike: "Honda Click 160 / ADV 160",
    startPoint: "Patong Beach",
    parkingInfo: "Popüler yerlerde otopark kalabalık olabilir",
    stops: [
      {
        order: 1,
        name: "Samet Nangshe Viewpoint",
        distance: "22 km",
        duration: "45 min",
        description: "Ünlü 3 koyun manzarası, Instagram fotoğrafları.",
      },
      {
        order: 2,
        name: "Promthep Cape",
        distance: "26 km",
        duration: "45 min",
        description: "Phuket'in en görkemli günbatışı noktası.",
      },
      {
        order: 3,
        name: "Karon Viewpoint",
        distance: "20 km",
        duration: "40 min",
        description: "Son fotoğraflar için ekstra açı.",
      },
      {
        order: 4,
        name: "Patong Geri Dönüş",
        distance: "12 km",
        duration: "30 min",
        description: "Akşam yemeği için Patong'a geri dön.",
      },
    ],
    safetyTips: [
      {
        icon: "📸",
        title: "Fotoğraf Çekmek",
        text: "Yolun kenarına dikkat et, dikkati dağılmasın.",
      },
      {
        icon: "🌅",
        title: "Işık Durumu",
        text: "Gün batarken karanlık hızlı gelir. Işıkları aç.",
      },
      {
        icon: "👥",
        title: "Kalabalık Yerler",
        text: "Popüler noktalar turist dolusu olabilir.",
      },
    ],
  },
  {
    id: "khao-sok",
    name: "Khao Sok Macerası",
    tagline: "Ormanlar ve Cheow Lan Lake",
    difficulty: "Zor",
    distance: "130 km",
    duration: "6-7 saat",
    elevation: "800 m",
    bestTime: "Erkek başı saatleri",
    image: "https://images.pexels.com/photos/1619317/pexels-photo-1619317.jpeg?w=1200&q=90",
    description: "Khao Sok Macerası, engebeli yollarda sürüş ve orman deneyiminin en yoğun halini sunmaktadır. Bu 130 kilometrelik rota 6-7 saat sürer ve zorluk seviyesi yüksektir. Patong Beach'ten başladığınızda, Phang Nga üzerinden orman yollarına gireceğiniz ve dağlık bölgelerde ilerleyeceğiniz. Khao Sok Milli Parkı, Tayland'ın en eski ve büyük milli parkıdır ve 175 milyon yıl öncesine dayanan jura dönemine ait taş kaplaması barındırır. Cheow Lan Gölü, yapay bir su deposu olup, kireçtaşı tepeleri arasında türkuaz mavi rengiyle harikulade görünmektedir. Gölün çevresinde limestone kayaları yer almakta ve tüm manzara karanlık ormandan birden açılan gözlerimi şaşırtan bir kontrast oluşturur. Orman yolları çok dönüşlü ve dar olabilir, bu nedenle yavaş ve dikkatli bir şekilde ilerlemelisiniz. Yağmur riski oldukça yüksektir ve ormandaki görünürlük sınırlı olabilir. Tekne turu seçeneği mevcuttur ve gölü keşfetmek için mükemmel bir yoldur. Benzin tüketimi 8-10 litre olup maliyet 400-500 THB'dir.",
    highlights: "Cheow Lan Lake, Jungle Rides, Karst Mountains, National Park",
    recommendedBike: "Honda CB500X / BMW GS 310",
    startPoint: "Patong Beach Roundabout",
    parkingInfo: "Park giriş noktasında otopark",
    stops: [
      {
        order: 1,
        name: "Phang Nga Through",
        distance: "0 km",
        duration: "0 dakika",
        description: "Patong'dan başla Phang Nga yoluna gir.",
      },
      {
        order: 2,
        name: "Jungle Riding Section",
        distance: "90 km",
        duration: "120 dakika",
        description: "Ormanlık engebeli yollarda sürüş.",
      },
      {
        order: 3,
        name: "Cheow Lan Lake",
        distance: "130 km",
        duration: "60 dakika",
        description: "Muhteşem türkuaz gölü görmek.",
      },
      {
        order: 4,
        name: "Tekne Turu İsteğe Bağlı",
        distance: "0 km",
        duration: "120 dakika",
        description: "Gölde tekneyle gezinti yapma imkanı.",
      },
    ],
    safetyTips: [
      {
        icon: "🌧️",
        title: "Yağmur İhtiyatı",
        text: "Ormanda ani yağmurlar sık olur.",
      },
      {
        icon: "🛞",
        title: "Tekerlek Durumu",
        text: "Engebeli yollar lastikleri çabuk yıpratır.",
      },
      {
        icon: "🧭",
        title: "Yol Bulma",
        text: "GPS veya harita mutlaka taşı.",
      },
    ],
  },
  {
    id: "phang-nga-scenic",
    name: "Phang Nga Sahil Yolu",
    tagline: "James Bond Island ve kayalık körfez",
    difficulty: "Kolay",
    distance: "95 km",
    duration: "5 saat",
    elevation: "300 m",
    bestTime: "Sabah erken",
    image: "https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?w=1200&q=90",
    description: "Phang Nga Sahil Yolu, ikonik James Bond Island'ını motordan görmek imkanı sunan spektaküler rotadır. Phang Nga Körfezi, dünya çapında ünlü kireçtaşı kayalıklarıyla kaplıdır ve bu 95 kilometrelik tur boyunca bu harikalar dizi göreceksiniz. Rota 5 saat sürer ve zorluk seviyesi düşüktür, çünkü yollar geniş ve iyi bakımlıdır. Patong'dan çıkarak Phang Nga yoluna girdikten sonra, körfez kenarı yolunu takip edeceksiniz. James Bond Island, 'The Man with the Golden Gun' filminde görülmüş ve o zamandan beri turist çekmektedir. Buranın etrafında kayak ve tekne turları mevcuttur. Samet Nangshe Viewpoint'ten körfezin harika manzarasını görebilirsiniz. Kayalık formasyonlar milyonlarca yıl içinde oluşmuş ve doğal olarak şekillenmiştir. Bu rotanın en iyi yönü, deniz kenarında sürüş yaptığınız hissidir ve taze deniz havası çok rahatlatıcıdır. Toplam benzin tüketimi 6-7 litre olup maliyet 300-400 THB'dir. Tekne turu ekstra 500-1500 THB'dir.",
    highlights: "Phang Nga Bay, James Bond Island, Samet Nangshe, Kayalık Formasyonlar",
    recommendedBike: "Honda Forza 350 / Yamaha NMAX",
    startPoint: "Patong Beach Roundabout",
    parkingInfo: "Tour operatörleri otopark sağlar",
    stops: [
      {
        order: 1,
        name: "Phang Nga Giriş",
        distance: "0 km",
        duration: "0 dakika",
        description: "Patong'dan çıkış.",
      },
      {
        order: 2,
        name: "James Bond Island Kayası",
        distance: "95 km",
        duration: "120 dakika",
        description: "Ünlü filmde kullanılan yer.",
      },
      {
        order: 3,
        name: "Kayak/Tekne Turu",
        distance: "0 km",
        duration: "120 dakika",
        description: "Suya inip çevreyi keşfet.",
      },
      {
        order: 4,
        name: "Patong Dönüş",
        distance: "95 km",
        duration: "120 dakika",
        description: "Geri dönüş sürüşü.",
      },
    ],
    safetyTips: [
      {
        icon: "☀️",
        title: "Güneş Koruyucu",
        text: "Su yansıması güneş ışınlarını artırır.",
      },
      {
        icon: "💰",
        title: "Tour Maliyeti",
        text: "Tekne turu ek ücretlidir.",
      },
      {
        icon: "🎫",
        title: "Giriş Ücreti",
        text: "Milli Park giriş ücreti var.",
      },
    ],
  },
  {
    id: "similan-islands",
    name: "Similan Adaları Dalış Turu",
    tagline: "Dünyanın en iyi dalış alanları",
    difficulty: "Orta",
    distance: "85 km",
    duration: "5 saat",
    elevation: "0 m",
    bestTime: "Sabah erken",
    image: "https://images.pexels.com/photos/1619317/pexels-photo-1619317.jpeg?w=1200&q=90",
    description: "Similan Adaları Dalış Turu, motosiklet ve sualtı sporu kombinasyonunu sunmaktadır. Dünya çapında en iyi dalış alanlarından biri olan Similan Adaları, tropikal balık türlerinin ve mercan resiflerin ana merkezi olarak bilinmektedir. Rota 85 kilometre olup motor bölümü 2 saat sürmektedir. Patong'dan çıkarak Phang Nga'ya gidecek ve oradan tekne kalkış noktasına transfer edileceksiniz. Tekne, Similan Island No. 4 ve No. 9'a götürecektir. Her alanda dalış yapacak ve mercan resifleri, anemone balıkları ve dev kaplumbağa görebilirsiniz. Dalış belirtileri (PADI Sertifikası) yarı profesyonel seviyelerde gerekli olabilir. Deniz durumu mevsime göre değişiklik gösterir; Kasım-Mayıs arasında en sakin, haziran-Ekim arasında daha dalgalıdır. Benzin tüketimi 5-6 litre olup maliyet 250-300 THB'dir. Dalış ve liveaboard paketi 4000-8000 THB arasında değişir.",
    highlights: "Similan Islands, Coral Reefs, Marine Life, Diving Sites",
    recommendedBike: "Honda ADV 160 / Forza 350",
    startPoint: "Patong Beach Roundabout",
    parkingInfo: "Liveaboard teknelere göre transfer sağlanır",
    stops: [
      {
        order: 1,
        name: "Phang Nga Transfer Point",
        distance: "85 km",
        duration: "120 dakika",
        description: "Tekne kalkış noktası.",
      },
      {
        order: 2,
        name: "Similan Island No.4",
        distance: "35 km by boat",
        duration: "90 dakika",
        description: "İlk dalış alanı.",
      },
      {
        order: 3,
        name: "Similan Island No.9",
        distance: "20 km by boat",
        duration: "90 dakika",
        description: "İkinci dalış alanı.",
      },
      {
        order: 4,
        name: "Geri Dönüş",
        distance: "85 km",
        duration: "120 dakika",
        description: "Patong'a dönüş.",
      },
    ],
    safetyTips: [
      {
        icon: "🤿",
        title: "Dalış Belgesi",
        text: "PADI belgesi gerekebilir.",
      },
      {
        icon: "🌊",
        title: "Deniz Durumu",
        text: "Mevsime göre deniz tehlikeli olabilir.",
      },
      {
        icon: "⏰",
        title: "Erken Başla",
        text: "Tekne sabah erken kalkıyor.",
      },
    ],
  },
  // ADDITIONAL TIER-2 ROUTES
  {
    id: "viewpoints-loop",
    name: "Phuket Viewpoints Loop",
    tagline: "Tüm manzara noktaları bir turu",
    difficulty: "Kolay",
    distance: "72 km",
    duration: "3.5 saat",
    elevation: "450 m",
    bestTime: "Sabah 09:00",
    image: "https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?w=1200&q=90",
    description: "Phuket Viewpoints Loop, Phuket'in tüm ünlü manzara noktalarını bir günde gezme imkanı sunar. Bu 72 kilometrelik tur 3,5 saatte tamamlanabilir. Radar Hill'den başlarsınız; burası adında anlaşılacağı gibi radar istasyonunun bulunduğu ve Phuket'in batı kısmının tam görünüşünü sunan yüksek bir tepe noktasıdır. Windmill Viewpoint, eski rüzgar değirmenleri kalıntılarının etrafında yer almakta ve geniş bir açıdan Phuket'i görmektedir. Samet Nangshe, üç koyun manzarası ile meşhur olup fotoğraf severler için parasal değeri yüksek konumdur. Promthep Cape'de günbatışı fotoğrafları çekeceğiniz için en iyi vakit 17:00-18:30 arasıdır. Tüm bu noktaları takip etmek, gün boyunca Phuket'in farklı açılarını görmek anlamına gelir. Benzin tüketimi 5-6 litre olup maliyet 250-300 THB'dir. Bu rota hiç Phuket'te olmayan ve bir gün içinde ana attraksiyonları görmek isteyenler için ideal olup, zaman yönetimi önem taşır.",
    highlights: "Radar Hill, Windmill, Samet Nangshe, Karon Viewpoint, Promthep",
    recommendedBike: "Honda Click 160",
    startPoint: "Patong Beach",
    parkingInfo: "Her yerde otopark var",
    stops: [
      {
        order: 1,
        name: "Radar Hill",
        distance: "28 km",
        duration: "50 min",
        description: "İlk manzara noktası.",
      },
      {
        order: 2,
        name: "Windmill Viewpoint",
        distance: "35 km",
        duration: "45 min",
        description: "İkinci nokta.",
      },
      {
        order: 3,
        name: "Samet Nangshe",
        distance: "22 km",
        duration: "40 min",
        description: "Üçüncü nokta.",
      },
      {
        order: 4,
        name: "Promthep Cape",
        distance: "26 km",
        duration: "50 min",
        description: "Son manzara noktası.",
      },
    ],
    safetyTips: [
      {
        icon: "📸",
        title: "Fazla Duruş",
        text: "Çok fotoğraf = uzun gün.",
      },
      {
        icon: "⏰",
        title: "Zaman Yönetimi",
        text: "Her yerde 20-30 dakika kal.",
      },
      {
        icon: "🚗",
        title: "Otopark",
        text: "Popüler saatlarda kalabalık olabilir.",
      },
    ],
  },
  {
    id: "beaches-hopping",
    name: "Phuket Beach Hopping",
    tagline: "Plajdan plaja sörfü deneme",
    difficulty: "Kolay",
    distance: "65 km",
    duration: "3 saat",
    elevation: "200 m",
    bestTime: "Sabah 08:00",
    image: "https://images.pexels.com/photos/1619317/pexels-photo-1619317.jpeg?w=1200&q=90",
    description: "Phuket Beach Hopping, Phuket'in en iyi plajlarını sürüş yaparak ziyaret etmek için tasarlanmış bir turdur. Bu 65 kilometrelik rota 3 saat sürer ve zorluk seviyesi çok düşüktür. Patong Beach'ten başlarsınız; bu Phuket'in en ünlü ve en kalabalık plajıdır ve yüzmek için mükemmel konumlanmıştır. Kata Beach, sörf deneyimi arayan kişiler için idealdir ve düzenli dalgalar barındırmaktadır. Karon Beach, aileler için daha sakin bir ortam sunar ve uzun kumlu plajıyla bilinmektedir. Bang Tao Beach, lüks resort ve spa merkezlerinin bulunduğu ve daha rafine bir bölgedir. Nai Harn Beach, Phuket'in en sakin ve güzel plajlarından biri olup, turist kalabalığından uzakta bir seçenek sunmaktadır. Tüm bu plajlara gitmek, Phuket'in çeşitli yaşam tarzlarını görmek demektir. Benzin tüketimi 4-5 litre olup maliyet 200-250 THB'dir. Plaj aktiviteleri ek maliyet gerektirir.",
    highlights: "Patong, Kata, Karon, Bang Tao, Nai Harn",
    recommendedBike: "Honda Click 160 / ADV 160",
    startPoint: "Patong Beach",
    parkingInfo: "Tüm plajlarda otopark var",
    stops: [
      {
        order: 1,
        name: "Patong Beach",
        distance: "0 km",
        duration: "30 min",
        description: "Başlangıç noktası.",
      },
      {
        order: 2,
        name: "Kata Beach",
        distance: "15 km",
        duration: "30 min",
        description: "Sörf plajı.",
      },
      {
        order: 3,
        name: "Karon Beach",
        distance: "5 km",
        duration: "30 min",
        description: "Aile plajı.",
      },
      {
        order: 4,
        name: "Bang Tao Beach",
        distance: "22 km",
        duration: "30 min",
        description: "Geniş plaj, lüks resort.",
      },
    ],
    safetyTips: [
      {
        icon: "🏊",
        title: "Yüzme Dikkat",
        text: "Her plajda dalga ve akıntı var.",
      },
      {
        icon: "🚗",
        title: "Sürüş Yolu",
        text: "Patong yol trafik yoğun olabilir.",
      },
      {
        icon: "💰",
        title: "Parking Ücreti",
        text: "Bazı plajlarda parking parasız değil.",
      },
    ],
  },
  {
    id: "hidden-gems",
    name: "Phuket Hidden Gems Route",
    tagline: "Az bilinen gizli mekanlar",
    difficulty: "Orta",
    distance: "80 km",
    duration: "4 saat",
    elevation: "350 m",
    bestTime: "Sabah 08:00",
    image: "https://images.pexels.com/photos/1181690/pexels-photo-1181690.jpeg?w=1200&q=90",
    description: "Phuket Hidden Gems Route, turist rehberlerinde olmayan gizli yerler keşfet için tasarlanmıştır. Bu 80 kilometrelik rota 4 saat sürer ve zorluk seviyesi orta düzeydedir. Soi Dog Foundation, köpek kurtarma merkezi olup hayvan sevenler için duygu yüklü bir deneyim sunmaktadır. Yerel rehabilitasyon çalışmalarını görmek ve köpekleri sevmek mümkündür. Bang Tao Temple, tarihi bir yapı olup yerel Budist inancının merkezini oluşturmaktadır. Sirinat Milli Parkı, doğa koruması alanı olup deniz kaplumbağalarının yuva yapma yerleri içerir. Freedom Beach, Patong'a yakın olup özel bir plaj olarak bilinmektedir ve az kişili olması sebebiyle sakindir. Bu tür yerler yerel kültürü anlamak ve Phuket'in yalnızca turist bölgelerinden öte kısımlarını görmek için önemlidir. Benzin tüketimi 5-6 litre olup maliyet 250-300 THB'dir. Gizli yerler harita olmadan bulunması zor olabilir çünkü işaret sayısı sınırlıdır.",
    highlights: "Soi Dog, Bang Tao Temple, Sirinat Park, Freedom Beach",
    recommendedBike: "Honda ADV 160",
    startPoint: "Patong Beach",
    parkingInfo: "Orta düzeyde otopark",
    stops: [
      {
        order: 1,
        name: "Soi Dog Foundation",
        distance: "15 km",
        duration: "45 min",
        description: "Köpek kurtarma merkezi.",
      },
      {
        order: 2,
        name: "Bang Tao Temple",
        distance: "22 km",
        duration: "45 min",
        description: "Tarihi tapınak.",
      },
      {
        order: 3,
        name: "Sirinat National Park",
        distance: "18 km",
        duration: "45 min",
        description: "Doğa koruma alanı.",
      },
      {
        order: 4,
        name: "Freedom Beach",
        distance: "8 km",
        duration: "45 min",
        description: "Sakin plaj.",
      },
    ],
    safetyTips: [
      {
        icon: "🗺️",
        title: "Harita Gerekli",
        text: "GPS veya offline harita taşı.",
      },
      {
        icon: "🚗",
        title: "Dar Yollar",
        text: "Bazı yollar dar ve engebeli.",
      },
      {
        icon: "👥",
        title: "Yerel İnsanlar",
        text: "Saygılı ol, sakin bölgeler.",
      },
    ],
  },
  {
    id: "night-ride",
    name: "Phuket Gece Sürüşü",
    tagline: "Neon ışığında şehir turu",
    difficulty: "Kolay",
    distance: "35 km",
    duration: "2 saat",
    elevation: "100 m",
    bestTime: "20:00-23:00",
    image: "https://images.pexels.com/photos/1619317/pexels-photo-1619317.jpeg?w=1200&q=90",
    description: "Phuket Gece Sürüşü, Patong'un neon ışıklarında şehir turunu sunmaktadır. Bu 35 kilometrelik rota 2 saat sürer ve zorluk seviyesi çok düşüktür; ancak gece sürüş dikkati gerektirir. Bangla Road, Patong'un en canlı gece hayatı merkezidir ve barlar, restoranlar ve nightclub'larla doludur. Patong Walking Street, haftada üç gün açık olan ve yerel ürünler satılan bir pazardır. Nightclub alanında dansçılar ve müzik bulunmakta, çok insanlı ve enerjik bir ortam yaratılmaktadır. Patong Beach'in gece ışıkları, özellikle iş merkezlerinin ışıklandırması altında çok güzel görünmektedir. Bu turda sürüş koşulları zor olabilir: trafik yoğun, kaldırımlar dar ve dikkat dağıtıcı unsurlar fazladır. Alkol kesinlikle almayın; taksi veya tuk-tuk kullanın. Işıklar her zaman açık olmalı ve motosikletiniz görülür durumda olmalıdır. Benzin tüketimi 2-3 litre olup maliyet 100-150 THB'dir.",
    highlights: "Bangla Road, Patong Walking Street, Nightclubs, Restaurants",
    recommendedBike: "Honda Click 160 / ADV 160",
    startPoint: "Patong Hotel",
    parkingInfo: "Nightclubs genellikle valet parking sunuyor",
    stops: [
      {
        order: 1,
        name: "Bangla Road Start",
        distance: "0 km",
        duration: "30 min",
        description: "Ana gece hayatı alanı.",
      },
      {
        order: 2,
        name: "Patong Walking Street",
        distance: "3 km",
        duration: "30 min",
        description: "Yürüyüş sokağı ve pazarlar.",
      },
      {
        order: 3,
        name: "Nightclub Area",
        distance: "5 km",
        duration: "45 min",
        description: "Gündüz kulüpleri.",
      },
      {
        order: 4,
        name: "Patong Beach Night",
        distance: "8 km",
        duration: "30 min",
        description: "Plaj gece manzarası.",
      },
    ],
    safetyTips: [
      {
        icon: "💡",
        title: "Işıklar Aç",
        text: "Gece motosikleti görülür hale getir.",
      },
      {
        icon: "🚔",
        title: "Polis Kontrolleri",
        text: "Gece hız kontrolleri sık olur.",
      },
      {
        icon: "🍻",
        title: "Alkol",
        text: "Eğer içersen, sürme. Taksi al.",
      },
    ],
  },
  {
    id: "couple-romance",
    name: "Çiftler İçin Romantik Rota",
    tagline: "Günbatışı ve romantik öğle yemeği",
    difficulty: "Kolay",
    distance: "60 km",
    duration: "3.5 saat",
    elevation: "300 m",
    bestTime: "14:00-18:30",
    image: "https://images.pexels.com/photos/1181690/pexels-photo-1181690.jpeg?w=1200&q=90",
    description: "Çiftler İçin Romantik Rota, sevgililerin Phuket'te güzel bir gün geçirmesi için tasarlanmıştır. Bu 60 kilometrelik tur 3,5 saat sürer ve zorluk seviyesi çok düşüktür. Samet Nangshe'de fotoğraf çekmek için durursunuz; buradaki 3-koyun manzarası çiftlerin sevgiliye manzara göstermesi için ideal bir noktadır. Beachfront restoranında öğle yemeği yaparsınız; deniz kenarı manzarası altında yemek yemek romantiktir. Promthep Cape'de günbatışını izlersiniz; bu gün ve doğanın en muhteşem anıdır. Akşam yemeği, yakın restoranlardan birinde yapılır. Tüm bu deneyim çiftlerin birlikte güzel anılar yaratmasını sağlar. Motosiklet sürüşü rahat ve yavaş olmalı, hız kontrolü mutlaktır. İyi giyinmek ve kişisel bakım önem taşır. Benzin tüketimi 4-5 litre olup maliyet 200-250 THB'dir. Toplam bütçe (yemekler, fotoğraflar, benzin) yaklaşık 500-1000 THB olup bu rota tüm çiftler için tavsiye edilir.",
    highlights: "Romantic Viewpoints, Beachfront Restaurants, Sunset Photography",
    recommendedBike: "Honda Click 160 / Forza 350",
    startPoint: "Patong Hotel",
    parkingInfo: "Restoranlar valet parking sunarlar",
    stops: [
      {
        order: 1,
        name: "Samet Nangshe",
        distance: "22 km",
        duration: "50 min",
        description: "İlk fotoğraf noktası.",
      },
      {
        order: 2,
        name: "Beachfront Restaurant",
        distance: "26 km",
        duration: "120 min",
        description: "Öğle yemeği yap.",
      },
      {
        order: 3,
        name: "Promthep Cape",
        distance: "26 km",
        duration: "60 min",
        description: "Günbatışı fotoğrafları.",
      },
      {
        order: 4,
        name: "Romantic Dinner",
        distance: "12 km",
        duration: "120 min",
        description: "Akşam yemeği.",
      },
    ],
    safetyTips: [
      {
        icon: "🏍️",
        title: "Rahat Sürüş",
        text: "Güvenli ve rahat hız tut.",
      },
      {
        icon: "📸",
        title: "Fotoğraflar",
        text: "Fotoğraf çekmek için durma noktalarında kal.",
      },
      {
        icon: "💅",
        title: "Görünüm",
        text: "Iyi giyindikten sonra sürüş yap.",
      },
    ],
  },
  {
    id: "adventure-extreme",
    name: "Macera Severler İçin Extreme Rota",
    tagline: "Engebeli yollar ve ormanlık sürüş",
    difficulty: "Zor",
    distance: "140 km",
    duration: "7 saat",
    elevation: "900 m",
    bestTime: "Erkek başı saatleri",
    image: "https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?w=1200&q=90",
    description: "Macera Severler İçin Extreme Rota, dört tekerlekli araçların gittiği yollara motosikletle çıkma macerasını sunmaktadır. Bu 140 kilometrelik rota 7 saat sürer ve zorluk seviyesi çok yüksektir. Jungle Trail'de ormanlık engebeli yollarda sürüş yaparsınız; bu yollar çoğu zaman tek şeritli ve dar olabilir. River Crossing, nehir geçişini içermekte ve motor/teker su içine girmektedir. Mountain Peak'te Phuket'in en yüksek noktalarına ulaşırsınız ve panoramik manzara göreceksiniz. Off-road yollarda motosikletin stabilite ve kontrol yeteneği çok önem taşır. Koruyucu ekipman (koruyucu ceket, eldiven, başlık ek koruma) mutlaktır. Alet kutusu ve harita/GPS taşımanız gerekmektedir. Hiçbir zaman yalnız gitmeyin, grup ile sürünüz. Araç bakım ve teknik bilgi gereklidir. Benzin tüketimi 10-12 litre olup maliyet 500-600 THB'dir. Bu rota sadece deneyimli sürücüler ve extreme spor meraklıları için tasarlanmıştır.",
    highlights: "Jungle Trails, Mountain Roads, River Crossings, Off-Road Sections",
    recommendedBike: "Honda CB500X / BMW GS 310",
    startPoint: "Patong Beach",
    parkingInfo: "Off-road park giriş",
    stops: [
      {
        order: 1,
        name: "Jungle Trail Start",
        distance: "35 km",
        duration: "90 min",
        description: "Orman sürüşü başla.",
      },
      {
        order: 2,
        name: "River Crossing",
        distance: "40 km",
        duration: "90 min",
        description: "Irmak geçişi.",
      },
      {
        order: 3,
        name: "Mountain Peak",
        distance: "35 km",
        duration: "90 min",
        description: "Dağ zirvesi.",
      },
      {
        order: 4,
        name: "Return to Base",
        distance: "30 km",
        duration: "90 min",
        description: "Geri dönüş.",
      },
    ],
    safetyTips: [
      {
        icon: "🛟",
        title: "Koruyucu Ekipman",
        text: "Tam koruyucu donanım gerekli.",
      },
      {
        icon: "🧰",
        title: "Alet Kutusu",
        text: "Harita ve araç tamiri gerekli.",
      },
      {
        icon: "👥",
        title: "Grup Sürüşü",
        text: "Asla yalnız git, grup ile sür.",
      },
    ],
  },
];
